package com.example.fakeshopping.utils

enum class LoginSignupStatus (val status:String){

    STATUS_LOGIN_SUCCESS("loginstatus_STATUS_LOGIN_SUCCESS"),
    STATUS_LOGIN_NO_USER("loginstatus_STATUS_LOGING_NO_USER"),
    STATUS_LOGIN_WRONG_PASSWORD ("loginstatus_STATUS_LOGING_WRONG_PASSWORD"),

    STATUS_INVALID_DETAILS ("loginstatus_STATUS_INVALID_DETAILS"),

    STATUS_SIGNUP_SUCCESS( "loginstatus_STATUS_SIGNUP_SUCCESS"),
    STATUS_SIGNUP_FAILED ( "loginstatus_STATUS_SIGNUP_FAILED"),
    STATUS_SIGNUP_INVALID_NAME( "loginstatus_STATUS_SIGNUP_INVALID_NAME"),
    STATUS_SIGNUP_INVALID_NUMBER ( "loginstatus_STATUS_SIGNUP_INVALID_NUMBER"),
    STATUS_SIGNUP_PASSWORD_UNMATCHED( "loginstatus_STATUS_PASSWORD_UNMATCHED"),

}